alter table "public"."platforms" drop constraint "platforms_name_key";

drop index if exists "public"."platforms_name_key";

create table "public"."announcements" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "color" text not null,
    "link" text,
    "removed_at" timestamp with time zone
);


alter table "public"."announcements" enable row level security;

alter table "public"."user_profiles" alter column "picture_url" set default 'https://mdixwlzweijevgjmcsmt.supabase.co/storage/v1/object/public/user_pictures/default'::text;

alter table "public"."user_profiles" alter column "picture_url" set not null;

alter table "public"."user_ratings" alter column "rating" set data type real using "rating"::real;

CREATE UNIQUE INDEX announcements_pkey ON public.announcements USING btree (id);

CREATE UNIQUE INDEX unique_user_game ON public.user_ratings USING btree (user_id, game_id);

alter table "public"."announcements" add constraint "announcements_pkey" PRIMARY KEY using index "announcements_pkey";

alter table "public"."user_ratings" add constraint "unique_user_game" UNIQUE using index "unique_user_game";

grant delete on table "public"."announcements" to "anon";

grant insert on table "public"."announcements" to "anon";

grant references on table "public"."announcements" to "anon";

grant select on table "public"."announcements" to "anon";

grant trigger on table "public"."announcements" to "anon";

grant truncate on table "public"."announcements" to "anon";

grant update on table "public"."announcements" to "anon";

grant delete on table "public"."announcements" to "authenticated";

grant insert on table "public"."announcements" to "authenticated";

grant references on table "public"."announcements" to "authenticated";

grant select on table "public"."announcements" to "authenticated";

grant trigger on table "public"."announcements" to "authenticated";

grant truncate on table "public"."announcements" to "authenticated";

grant update on table "public"."announcements" to "authenticated";

grant delete on table "public"."announcements" to "service_role";

grant insert on table "public"."announcements" to "service_role";

grant references on table "public"."announcements" to "service_role";

grant select on table "public"."announcements" to "service_role";

grant trigger on table "public"."announcements" to "service_role";

grant truncate on table "public"."announcements" to "service_role";

grant update on table "public"."announcements" to "service_role";

create policy "Enable read access for all users"
on "public"."announcements"
as permissive
for select
to public
using (true);


create policy "Enable insert for authenticated users only"
on "public"."user_ratings"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable update for authenticated users only"
on "public"."user_ratings"
as permissive
for update
to authenticated
using (true);



